name: listify_mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.6.0
  google_sign_in: ^6.2.1
  camera: ^0.11.0
  image_picker: ^1.1.0
  file_picker: ^8.0.5
  url_launcher: ^6.3.0
  html: ^0.15.4
  http: ^1.4.0
  cupertino_icons: ^1.0.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutterfire_cli: ^1.2.0

flutter:
  uses-material-design: true